name: Build

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: |
          npm install
          npm install --global web-ext
      - name: Build
        run: |
          npm run zip
          npm run zip:firefox
          mv .output/vostext-*-chrome.zip .output/vostext-chrome.unsigned.zip
          mv .output/vostext-*-firefox.zip .output/vostext-firefox.unsigned.zip
          mv .output/vostext-*-sources.zip .output/vostext-sources.zip
          cd .output/firefox-mv2
          set +e
          web-ext sign --channel=unlisted --api-key=${{ secrets.FIREFOX_API_KEY }} --api-secret=${{ secrets.FIREFOX_API_SECRET }}
          find .output/firefox-mv2/web-ext-artifacts -name "*.xpi" -exec mv {} .output/vostext-firefox.xpi \;
      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: firefox-extension
          path: .output/*.zip
            .output/*.xpi