name: Build

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        continue-on-error: true
        run: |
          npm run build
          npm run build:firefox          
      - name: Upload extension (chrome)
        uses: actions/upload-artifact@v6
        with:
          name: vostext-chrome.unsigned
          path: .output/chrome-mv3
      - name: Upload extension (firfox)
        uses: actions/upload-artifact@v6
        with:
          name: vostext-firefox.unsigned
          path: .output/firefox-mv2